# root user: root/example
# For use: bd - main; user - user/user
version: '3.1'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  test-seed:
    image: mongo
    links:
      - db
    command: "mongoimport -h db -u user -p user -d main /opt/data/dblpv13.jsonl"
    volumes:
      - ./test-data:/opt/data
    depends_on:
      - db

  main-seed:
    image: mongo
    links:
      - db
    command: "mongoimport -h db -u user -p user -d main /opt/data/dblpv13.jsonl"
    volumes:
      - ./data:/opt/data
    depends_on:
      - db

  tag-seed:
    image: mongo
    links:
      - db
    command: "mongoimport -h db -u user -p user -d main -c tags --type csv --headerline /opt/data/id_class.csv"
    volumes:
      - ./data:/opt/data
    depends_on:
      - db

  rec-data-seed:
    image: mongo
    links:
      - db
    command: "mongoimport -h db -u user -p user -d main -c author2author --type csv --headerline /opt/data/sim_matrix_class3.csv"
    volumes:
      - ./data:/opt/data
    depends_on:
      - db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    depends_on:
      - db

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: my-fastapi-app
    environment:
      MONGO_URI: mongodb://user:user@db:27017/main
      DB_NAME: main
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    command: "uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker_files/dashboard/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
      - mongodb-exporter
    ports:
      - 3000:3000
    volumes:
      - ./docker_files/dashboard/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - docker_files/dashboard/config.monitoring

  mongodb-exporter:
    image: ssheehy/mongodb-exporter:latest
    ports:
      - 9216:9216
    environment:
      MONGODB_URI: 'mongodb://mongodb_exporter:s3cr3tpassw0rd@db:27017/main?sslmode=disable'
    links:
      - db
      - prometheus
